### ISSUE TITLE
verification of yaml with --auto-convert fails for older format

### ISSUE THREAD

**Issue by maweigert** [bioimage-io/spec-bioimage-io#100]
Just noticed, that verification of the following 0.3.1 compliant spec fails with `--auto-convert`:

[model.yaml.zip](https://github.com/bioimage-io/spec-bioimage-io/files/6619983/model.yaml.zip)

```
# fails
python -m bioimageio.spec verify-spec  --auto-convert model.yaml
```

```
# old 0.3.1 branch works 
git checkout 709f6a5
python -m bioimageio.spec verify-spec  model.yaml
```

(i suspect the license field doesn't get converted)

**Comment by FynnBe** [comment]
yes, since 0.3.2 we require license to be a license identifier from the SPDX license list: https://spdx.org/licenses/  (https://github.com/bioimage-io/spec-bioimage-io#changelog)
`BSD 3-Clause License` is not a valid SPDX identifier (it should be `BSD-3-Clause`)

`--auto-convert` does not attempt to match the license (in <=0.3.1 any string is allowed). I think for the limited number of models in 0.3.1 adding this feature is not worth it.

Maybe we should allow for the full name as well? (In this case `BSD 3-Clause "New" or "Revised" License`)
@oeway @constantinpape what do you think about supporting the full name, too?

**Comment by maweigert** [comment]
Sure, I don't think its important that the license will get autoconverted, but I think that 

`python -m bioimageio.spec verify-spec model.yaml` 

should work even for specs with an older (yet valid) format, shouldn't it?

**Comment by FynnBe** [comment]
ah, I see, yes, I am working on it: https://github.com/bioimage-io/spec-bioimage-io/pull/99

**Comment by maweigert** [comment]
Cool, thx! :)

(background: I am currently automatically validate every spec export in stardist automatically with that code, so the version bump some days ago broke everything :)

**Comment by FynnBe** [comment]
very sorry, yet very glad to hear that. I suggest we'll be more strict with the versioning on master. Sorry for the inconvenience

**Comment by maweigert** [comment]
All good, I just got very confused :)

**Comment by FynnBe** [comment]
done
