### ISSUE TITLE
Add proper caching

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/spec-bioimage-io#289]
The current caching solution is appalling.
How about we use https://github.com/reclosedev/requests-cache ?
The default backend seem to be "sqlite", but "filesystem" is also supported, which--I only speculate--might be the better choice for weight files, etc. as we should share the cache across bioimageio.spec and bioimageio.core.
Features also include invalidating cache entries by age.

Obviously we need to add it as non-pyodide dependency (see #265).

@oeway @constantinpape @k-dominik any thoughts/comments?

**Comment by oeway** [comment]
I think we can also think about having a dedicated folder for models (instead of a cache for low level files), a bit similar to deepimagej does, we can place it under: `~/.bioimageio/models` (the location can be changed via an environment variable ). By default the python function will try to check the models location see if there is model with the same bioimageio id, if not, try to download it. We should also provide an argument to skip the cached version and force download.

**Comment by FynnBe** [comment]
Could we also enable/disable the cache via an environment variable?

**Comment by constantinpape** [comment]
> Could we also enable/disable the cache via an environment variable?

Would also work for me. What do you think @oeway?

**Comment by oeway** [comment]
I think a kwargs is much better. The reason is that we want to make it more explicit and can be switched on and off in the code easily. Environment variable will also work but not explicit enough and typically for global static setting.

As a general guideline, we should try to avoid golbal variables/state to make it more reliable and easy to debug —— a bit along the direction of pure functions in functional programming.

**Comment by FynnBe** [comment]
And `BIOIMAGEIO_CACHE_PATH` is also an env variable with a very similar impact. If we add a `cache` kwarg we would probably think of turning BIOIMAGEIO_CACHE_PATH into a `cache_path` kwarg as well for the same reasons and that just does not look good somehow 🤷

**Comment by constantinpape** [comment]
I think an environment variable is fine. For most users caching will not be a problem and is the desired behavior. For power users who want to deactivate it an env variable is fine. And this is preferable to changing this in all function signatures now, which has some potential to introduce bugs as well.

@oeway you're probably aware of this, but you can use `os.environ["ENV_VAR_NAME"] = "1"` to set environment variables, so you can simply do this in your python code.

**Comment by oeway** [comment]
I think we should go ahead and provide at least a way to disable it, it's better than nothing.

> @oeway you're probably aware of this, but you can use os.environ["ENV_VAR_NAME"] = "1" to set environment variables, so you can simply do this in your python code.

Yes, I know. What I want to stress is that using a env is not a good option, it's a global state that can be changed outside the scope of your code, e.g. it can cause wired issue if you have multiple thread or subprocesses, changing cache setting in one thread will affect another one.

Therefore, I think it's ok to be progressive, but we need to be aware the issue will exists.

I mentioned the pure function doesn't mean we need to make all the functions pure, which is not possible, but we should try to reduce the impurity to make the code easier to debug and run in parallel sessions.

**Comment by FynnBe** [comment]
no-cache option implemented in https://github.com/bioimage-io/spec-bioimage-io/pull/423

**Comment by FynnBe** [comment]
we cache with pooch by now and users can set the `bioimageio_cache_path` env var
