### ISSUE TITLE
Keyword missing: download_url

### ISSUE THREAD

**Issue by tomburke-rse** [bioimage-io/spec-bioimage-io#379]
While testing the java produced rdf files, I noticed a missing field: **download_url**

> Error: {
>   "name": "{name: modelname, ...}",
>   "source_name": "{name: modelname, ...}",
>   "error": "(\"__init__() got an unexpected keyword argument 'download_url'\", \"when initializing <class 'bioimageio.spec.model.v0_4.raw_nodes.Model'> from <Model(many=False)>\")",
>   "warnings": {},
>   "traceback": [
>     "  File \"/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 73, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_format=\"latest\" if update_format else None)\n",
>     "  File \"/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 195, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
>     "  File \"/lib/python3.9/site-packages/marshmallow/schema.py\", line 719, in load\n    return self._do_load(\n",
>     "  File \"/lib/python3.9/site-packages/marshmallow/schema.py\", line 892, in _do_load\n    result = self._invoke_load_processors(\n",
>     "  File \"/lib/python3.9/site-packages/marshmallow/schema.py\", line 1090, in _invoke_load_processors\n    data = self._invoke_processors(\n",
>     "  File \"/lib/python3.9/site-packages/marshmallow/schema.py\", line 1220, in _invoke_processors\n    data = processor(data, many=many, **kwargs)\n",
>     "  File \"/lib/python3.9/site-packages/bioimageio/spec/shared/schema.py\", line 34, in make_object\n    raise e\n",
>     "  File \"/lib/python3.9/site-packages/bioimageio/spec/shared/schema.py\", line 31, in make_object\n    return this_type(**data)\n"
>   ],
>   "nested_errors": {}
> }

**Comment by constantinpape** [comment]
Thanks for reporting this @tomburke-rse. Could you please upload the model that produces the error somewhere so that we have a test case?

**Comment by constantinpape** [comment]
> Sure. Not the greatest example and still work in progress

No worries, we just need something that triggers the error. @FynnBe could you look into fixing this?

**Comment by FynnBe** [comment]
interesting case... 
yeah, so we decided at some point to have `download_url` only in non-model RDFs, because we had the special downloader for model RDFs and thus no need for `download_url`. That it does show up in the documentation for the model RDF is a bug. I disallowed it by setting it to `missing`, but this seems to be ignored for the doc generation: https://github.com/bioimage-io/spec-bioimage-io/blob/d9ab98783210feb45d35bc63d8a5f65c7fab8d34/bioimageio/spec/model/v0_4/schema.py#L287

I would like to quickly bring up the question if we could not remove the `download_url` field from all RDFs to keep the RDF itself as sole source of truth and not just pointer to another packaged version...
If we do decide we want to keep it we should allow it for model RDFs as well.
Either way I'll update the spec library, but let's get some votes from @constantinpape @tomburke-rse @oeway @esgomezm to determine the fate of `download_url` 🍀 💀?

**Comment by constantinpape** [comment]
I don't have a strong opinion here. For now I would vote to remove the `download_url`, unless we have a good reason to include it for the general rdf.

**Comment by oeway** [comment]
We used download_url for datasets and notebooks etc. I would rather keep  it, breaking stuff for non-critical fields is not nice. I would rather add it to the model spec as a non-breaking change. For the model one can still use that to point to a pre-generated model package that contains all the weight format. It's an optional field, so you don't need to use it if you don't like it.

As a general strategy, I would allow any fields that are already defined in the general RDF in the model RDF, we have fixed the source key and there is no conflicting keys, so it won't worth to make validator fail for those additional but known keys.

Plus, removing it from other RDF types won't make a difference because they allow arbitrary fields anyway.

**Comment by constantinpape** [comment]
> For the model one can still use that to point to a pre-generated model package that contains all the weight format. It's an optional field, so you don't need to use it if you don't like it.

That would also be fine with me.

**Comment by tomburke-rse** [comment]
We currently use the field to link to the zipped package, a relict from the pre-zenodo times. I don't have a strong opinion either on it, but I think Wei's proposal is the best way to go, since the field is already in the general RDF.

**Comment by constantinpape** [comment]
Ok, let's go with Wei's proposal then. Can you implement it @FynnBe? (And once it's done I think we can bump to the next version)

**Comment by FynnBe** [comment]
implemented in https://github.com/bioimage-io/spec-bioimage-io/pull/382

**Comment by oeway** [comment]
Great, thanks @FynnBe and everyone involved in the discussion.
